import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  base: './', // 👈 ensures relative paths for CSS/JS
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "@shared": path.resolve(__dirname, "../shared"),
      "@assets": path.resolve(__dirname, "../attached_assets"),
    },
  },
  root: __dirname,
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      external: [
        'zod',
        'react-hook-form',
        '@hookform/resolvers',
        '@radix-ui/react-toast',
        '@radix-ui/react-accordion',
        '@radix-ui/react-alert-dialog',
        '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-avatar',
        '@radix-ui/react-checkbox',
        '@radix-ui/react-collapsible',
        '@radix-ui/react-context-menu',
        '@radix-ui/react-dialog',
        '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-hover-card',
        '@radix-ui/react-label',
        '@radix-ui/react-menubar',
        '@radix-ui/react-navigation-menu',
        '@radix-ui/react-popover',
        '@radix-ui/react-progress',
        '@radix-ui/react-radio-group',
        '@radix-ui/react-scroll-area',
        '@radix-ui/react-select',
        '@radix-ui/react-separator',
        '@radix-ui/react-slider',
        '@radix-ui/react-slot',
        '@radix-ui/react-switch',
        '@radix-ui/react-tabs',
        '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group',
        '@radix-ui/react-tooltip',
        'react',
        'react-dom',
        'react-icons',
        'framer-motion',
        'lucide-react',
        'class-variance-authority',
        'clsx',
        'tailwind-merge',
        'tailwindcss-animate',
        'date-fns',
        'react-day-picker',
        'cmdk',
        'embla-carousel-react',
        'input-otp',
        'jspdf',
        'react-resizable-panels',
        'recharts',
        'vaul',
        'wouter',
        '@tanstack/react-query',
        'drizzle-orm',
        'drizzle-zod',
        'zod-validation-error'
      ],
    },
  },
});

